import os
from dotenv import load_dotenv

load_dotenv()

# --- TWILIO CONFIGURATION ---
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")

# --- QDRANT CONFIGURATION ---
QDRANT_URL = os.getenv("QDRANT_URL")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")

# --- GEMINI CONFIGURATION ---
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# --- MODEL PATHS ---
YOLO_MODEL_PATH = os.getenv("YOLO_MODEL_PATH")
MODEL_A_PATH = os.getenv("VIDEOMAE_MODEL_PATH")

# --- MODEL PARAMETERS ---
NUM_FRAMES = 16
WEAPON_CLASSES = ["Gun", "Knife"]

# --- DETECTION THRESHOLDS ---
CONFIDENCE_THRESHOLD_MOTION = 0.95
CONFIDENCE_THRESHOLD_OBJECT = 0.60
DEBOUNCE_COUNT = 3
STATIC_FRAME_MOTION_THRESHOLD = 5

# --- VIDEO PROCESSING ---
TARGET_CLIP_SIZE_MB = 9.5
REALTIME_FRAME_SKIP = 2
BUFFER_SECONDS = 5
POST_ROLL_FRAMES = 50

# --- PATHS ---
UPLOAD_FOLDER: str = "uploads"
CLIPS_FOLDER: str = "clips"
TEMP_FOLDER: str = "temp"

# --- ALERTING ---
ALERT_COOLDOWN_SECONDS = 600  # 10 minutes
